# Generated by Django 3.2.5 on 2021-07-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_pub_data_blog_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='wirter',
            new_name='writer',
        ),
    ]
